---
uk:
  GB:
  - United Kingdom
  - GBR
  JE:
  - Jersey
  - JEY
europe:
  AL:
  - Albania
  - ALB
  AD:
  - Andorra
  - AND
  AM:
  - Armenia
  - ARM
  AT:
  - Austria
  - AUT
  AZ:
  - Azerbaijan
  - AZE
  BY:
  - Belarus
  - BLR
  BE:
  - Belgium
  - BEL
  BA:
  - Bosnia and Herzegovina
  - BIH
  BG:
  - Bulgaria
  - BGR
  HR:
  - Croatia
  - HRV
  CY:
  - Cyprus
  - CYP
  CZ:
  - Czech Republic
  - CZE
  DK:
  - Denmark
  - DNK
  EE:
  - Estonia
  - EST
  FO:
  - Faroe Islands
  - FRO
  FI:
  - Finland
  - FIN
  FR:
  - France
  - FRA
  GE:
  - Georgia
  - GEO
  DE:
  - Germany
  - DEU
  GI:
  - Gibraltar
  - GIB
  GR:
  - Greece
  - GRC
  GL:
  - Greenland
  - GRL
  HU:
  - Hungary
  - HUN
  IS:
  - Iceland
  - ISL
  IE:
  - Ireland
  - IRL
  IT:
  - Italy
  - ITA
  KZ:
  - Kazakhstan
  - KAZ
  XK:
  - Kosovo
  - XKO
  KG:
  - Kyrgyzstan
  - KGZ
  LV:
  - Latvia
  - LVA
  LI:
  - Liechtenstein
  - LIE
  LT:
  - Lithuania
  - LTU
  LU:
  - Luxembourg
  - LUX
  MK:
  - Macedonia
  - MKD
  MT:
  - Malta
  - MLT
  MD:
  - Moldova
  - MDA
  MC:
  - Monaco
  - MCO
  ME:
  - Montenegro
  - MNE
  NL:
  - Netherlands
  - NLD
  'NO':
  - Norway
  - NOR
  PL:
  - Poland
  - POL
  PT:
  - Portugal
  - PRT
  RO:
  - Romania
  - ROU
  RU:
  - Russia
  - RUS
  SM:
  - San Marino
  - SMR
  RS:
  - Serbia
  - SRB
  SK:
  - Slovakia
  - SVK
  SI:
  - Slovenia
  - SVN
  ES:
  - Spain
  - ESP
  SJ:
  - Svalbard and Jan Mayen
  - SJM
  SE:
  - Sweden
  - SWE
  CH:
  - Switzerland
  - CHE
  TJ:
  - Tajikistan
  - TJK
  TR:
  - Turkey
  - TUR
  TM:
  - Turkmenistan
  - TKM
  UA:
  - Ukraine
  - UKR
  UZ:
  - Uzbekistan
  - UZB
  VA:
  - Vatican City
  - VAT
world:
  AE:
  - United Arab Emirates
  - ARE
  AF:
  - Afghanistan
  - AFG
  AG:
  - Antigua and Barbuda
  - ATG
  AI:
  - Anguilla
  - AIA
  AN:
  - Netherlands Antilles
  - ANT
  AO:
  - Angola
  - AGO
  AQ:
  - Antarctica
  - ATA
  AR:
  - Argentina
  - ARG
  AS:
  - American Samoa
  - ASM
  AU:
  - Australia
  - AUS
  AW:
  - Aruba
  - ABW
  AX:
  - "Åland Islands"
  - ALA
  BB:
  - Barbados
  - BRB
  BD:
  - Bangladesh
  - BGD
  BF:
  - Burkina Faso
  - BFA
  BH:
  - Bahrain
  - BHR
  BI:
  - Burundi
  - BDI
  BJ:
  - Benin
  - BEN
  BL:
  - Saint Barthélemy
  - BLM
  BM:
  - Bermuda
  - BMU
  BN:
  - Brunei
  - BRN
  BO:
  - Bolivia
  - BOL
  BQ:
  - Bonaire, Sint Eustatius and Saba
  - BES
  BR:
  - Brazil
  - BRA
  BS:
  - Bahamas
  - BHS
  BT:
  - Bhutan
  - BTN
  BV:
  - Bouvet Island
  - BVT
  BW:
  - Botswana
  - BWA
  BZ:
  - Belize
  - BLZ
  CA:
  - Canada
  - CAN
  CC:
  - Cocos (Keeling) Islands
  - CCK
  CD:
  - Congo (Dem. Rep.)
  - COD
  CF:
  - Central African Republic
  - CAF
  CG:
  - Congo
  - COG
  CI:
  - Côte D'Ivoire
  - CIV
  CK:
  - Cook Islands
  - COK
  CL:
  - Chile
  - CHL
  CM:
  - Cameroon
  - CMR
  CN:
  - China
  - CHN
  CO:
  - Colombia
  - COL
  CR:
  - Costa Rica
  - CRI
  CU:
  - Cuba
  - CUB
  CV:
  - Cape Verde
  - CPV
  CW:
  - Curaçao
  - CUW
  CX:
  - Christmas Island
  - CXR
  DJ:
  - Djibouti
  - DJI
  DM:
  - Dominica
  - DMA
  DO:
  - Dominican Republic
  - DOM
  DZ:
  - Algeria
  - DZA
  EC:
  - Ecuador
  - ECU
  EG:
  - Egypt
  - EGY
  EH:
  - Western Sahara
  - ESH
  ER:
  - Eritrea
  - ERI
  ET:
  - Ethiopia
  - ETH
  FJ:
  - Fiji
  - FJI
  FK:
  - Falkland Islands
  - FLK
  FM:
  - Micronesia
  - FSM
  GA:
  - Gabon
  - GAB
  GD:
  - Grenada
  - GRD
  GF:
  - French Guiana
  - GUF
  GG:
  - Guernsey and Alderney
  - GGY
  GH:
  - Ghana
  - GHA
  GM:
  - Gambia
  - GMB
  GN:
  - Guinea
  - GIN
  GP:
  - Guadeloupe
  - GLP
  GQ:
  - Equatorial Guinea
  - GNQ
  GS:
  - South Georgia and the South Sandwich Islands
  - SGS
  GT:
  - Guatemala
  - GTM
  GU:
  - Guam
  - GUM
  GW:
  - Guinea-Bissau
  - GNB
  GY:
  - Guyana
  - GUY
  HK:
  - Hong Kong
  - HKG
  HM:
  - Heard and McDonald Islands
  - HMD
  HN:
  - Honduras
  - HND
  HT:
  - Haiti
  - HTI
  ID:
  - Indonesia
  - IDN
  IL:
  - Israel
  - ISR
  IM:
  - Isle of Man
  - IMN
  IN:
  - India
  - IND
  IO:
  - British Indian Ocean Territory
  - IOT
  IQ:
  - Iraq
  - IRQ
  IR:
  - Iran
  - IRN
  JM:
  - Jamaica
  - JAM
  JO:
  - Jordan
  - JOR
  JP:
  - Japan
  - JPN
  KE:
  - Kenya
  - KEN
  KH:
  - Cambodia
  - KHM
  KI:
  - Kiribati
  - KIR
  KM:
  - Comoros
  - COM
  KN:
  - Saint Kitts and Nevis
  - KNA
  KP:
  - Korea (North)
  - PRK
  KR:
  - Korea (South)
  - KOR
  KW:
  - Kuwait
  - KWT
  KY:
  - Cayman Islands
  - CYM
  LA:
  - Laos
  - LAO
  LB:
  - Lebanon
  - LBN
  LC:
  - Saint Lucia
  - LCA
  LK:
  - Sri Lanka
  - LKA
  LR:
  - Liberia
  - LBR
  LS:
  - Lesotho
  - LSO
  LY:
  - Libya
  - LBY
  MA:
  - Morocco
  - MAR
  MF:
  - Saint Martin
  - MAF
  MG:
  - Madagascar
  - MDG
  MH:
  - Marshall Islands
  - MHL
  ML:
  - Mali
  - MLI
  MM:
  - Myanmar
  - MMR
  MN:
  - Mongolia
  - MNG
  MO:
  - Macao
  - MAC
  MP:
  - Northern Mariana Islands
  - MNP
  MQ:
  - Martinique
  - MTQ
  MR:
  - Mauritania
  - MRT
  MS:
  - Montserrat
  - MSR
  MU:
  - Mauritius
  - MUS
  MV:
  - Maldives
  - MDV
  MW:
  - Malawi
  - MWI
  MX:
  - Mexico
  - MEX
  MY:
  - Malaysia
  - MYS
  MZ:
  - Mozambique
  - MOZ
  NA:
  - Namibia
  - NAM
  NC:
  - New Caledonia
  - NCL
  NE:
  - Niger
  - NER
  NF:
  - Norfolk Island
  - NFK
  NG:
  - Nigeria
  - NGA
  NI:
  - Nicaragua
  - NIC
  NP:
  - Nepal
  - NPL
  NR:
  - Nauru
  - NRU
  NU:
  - Niue
  - NIU
  NZ:
  - New Zealand
  - NZL
  OM:
  - Oman
  - OMN
  PA:
  - Panama
  - PAN
  PE:
  - Peru
  - PER
  PF:
  - French Polynesia
  - PYF
  PG:
  - Papua New Guinea
  - PNG
  PH:
  - Philippines
  - PHL
  PK:
  - Pakistan
  - PAK
  PM:
  - Saint Pierre and Miquelon
  - SPM
  PN:
  - Pitcairn
  - PCN
  PR:
  - Puerto Rico
  - PRI
  PS:
  - Palestine
  - PSE
  PW:
  - Palau
  - PLW
  PY:
  - Paraguay
  - PRY
  QA:
  - Qatar
  - QAT
  RE:
  - Réunion
  - REU
  RW:
  - Rwanda
  - RWA
  SA:
  - Saudi Arabia
  - SAU
  SB:
  - Solomon Islands
  - SLB
  SC:
  - Seychelles
  - SYC
  SD:
  - Sudan
  - SDN
  SG:
  - Singapore
  - SGP
  SH:
  - Saint Helena
  - SHN
  SL:
  - Sierra Leone
  - SLE
  SN:
  - Senegal
  - SEN
  SO:
  - Somalia
  - SOM
  SR:
  - Suriname
  - SUR
  SS:
  - South Sudan
  - SSD
  ST:
  - São Tomé and Príncipe
  - STP
  SV:
  - El Salvador
  - SLV
  SX:
  - Sint Maarten
  - SXM
  SY:
  - Syria
  - SYR
  SZ:
  - Swaziland
  - SQZ
  TC:
  - Turks and Caicos Islands
  - TCA
  TD:
  - Chad
  - TCD
  TF:
  - French Southern Territories
  - ATF
  TG:
  - Togo
  - TGO
  TH:
  - Thailand
  - THA
  TK:
  - Tokelau
  - TKL
  TL:
  - East Timor
  - TLS
  TN:
  - Tunisia
  - TUN
  TO:
  - Tonga
  - TON
  TT:
  - Trinidad and Tobago
  - TTO
  TV:
  - Tuvalu
  - TUV
  TW:
  - Taiwan
  - TWN
  TZ:
  - Tanzania
  - TZA
  UG:
  - Uganda
  - UGA
  UM:
  - United States Minor Outlying Islands
  - UMI
  US:
  - United States of America
  - USA
  UY:
  - Uruguay
  - URY
  VC:
  - Saint Vincent and the Grenadines
  - VCT
  VE:
  - Venezuela
  - VEN
  VG:
  - British Virgin Islands
  - VGB
  VI:
  - Virgin Islands of the United States
  - VIR
  VN:
  - Vietnam
  - VNM
  VU:
  - Vanuatu
  - VUT
  WF:
  - Wallis and Futuna
  - WLF
  WS:
  - Samoa
  - WSM
  YE:
  - Yemen
  - YEM
  YT:
  - Mayotte
  - MYT
  ZA:
  - South Africa
  - ZAF
  ZM:
  - Zambia
  - ZMB
  ZW:
  - Zimbabwe
  - ZWE
